### ISSUE TITLE
Create Sample error

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#1100]
@igboyes 
After the latest fix, I seem to get the following error:
```
"POST /api/samples HTTP/1.1" 201 
Traceback (most recent call last):
  File "/home/naomis/Projects/virtool/virtool/jobs/job.py", line 75, in run method()
  File "/home/naomis/Projects/virtool/virtool/jobs/create_sample.py", line 96, in make_sample_dir analysis_path = os.path.join(self.sample_path, "analysis")
  File "/home/naomis/.virtualenvs/virtool/lib/python3.6/posixpath.py", line 80, in join a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap self.run()
  File "/home/naomis/Projects/virtool/virtool/jobs/job.py", line 87, in run self.cleanup()
  File "/home/naomis/Projects/virtool/virtool/jobs/create_sample.py", line 318, in cleanup
    for file_id in self.files:
TypeError: 'NoneType' object is not iterable

```

**Comment by igboyes** [comment]
I'll have a fix for this shortly.
