### ISSUE TITLE
KeyError in generate_isolate_fasta()

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1335]
Error during Pathoscope.

```
Traceback (most recent call last):
File "/drone/src/virtool/jobs/job.py", line 166, in run
File "/drone/src/virtool/jobs/pathoscope.py", line 183, in generate_isolate_fasta
File "/drone/src/virtool/jobs/pathoscope.py", line 183, in <setcomp>
KeyError: 1809
```
Occurs for CPH samples 17TFP192 and 17TFP194.

**Comment by igboyes** [comment]
This error was due to a instance-specific problem in a reference. One sequence had an empty string as an `_id`.

This problem will be avoided by more stringently validating API inputs (#1371).
