### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#1386]
```
Traceback (most recent call last):
File "/drone/src/virtool/jobs/job.py", line 166, in run
File "/drone/src/virtool/jobs/nuvs.py", line 104, in reunite_pairs
File "/drone/src/virtool/bio.py", line 159, in read_fastq
File "/usr/local/lib/python3.6/codecs.py", line 321, in decode
UnicodeDecodeError
```

Error is due to decompressed FASTQ data not being available.

**Comment by igboyes** [comment]
Has not recurred.
