### ISSUE TITLE
Exception when starting jobs

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#170]
```
Traceback (most recent call last):
  File "/home/igboyes/.virtualenvs/virtool/lib/python3.6/site-packages/motor/core.py", line 878, in _to_list
    to_list_future.set_result(the_list)
asyncio.base_futures.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48380)
  File "/home/igboyes/.virtualenvs/virtool/lib/python3.6/site-packages/motor/core.py", line 885, in _to_list
    to_list_future.set_exception(exc)
asyncio.base_futures.InvalidStateError: invalid state

```

**Comment by igboyes** [comment]
This may have been resolved by upgrade ``uvloop``.

**Comment by igboyes** [comment]
This was no resolved.

- it occurs only when the ``GET`` request is in response to the client receiving a websocket update
- it occurs especially after starting new jobs that result in rapid sequential websocket updates
