### ISSUE TITLE
KeyError: 'remove_directory'

### ISSUE THREAD

**Issue by tianshengsui** [virtool/virtool#1994]
This error happens when I start Virtool in release-5.0.0 branch:
```
2020-12-01 12:05:46  config      INFO     Found data path: ./vt/data
2020-12-01 12:05:46  startup     INFO     Virtool v4.1.1-118-gfa891d80
2020-12-01 12:05:46  startup     INFO     Mode: server
2020-12-01 12:05:46  startup     INFO     Connecting to MongoDB
2020-12-01 12:05:46  mongo       INFO     Found MongoDB 4.4.1
2020-12-01 12:05:46  startup     INFO     Starting dispatcher
2020-12-01 12:05:46  startup     INFO     Starting HTTP client
2020-12-01 12:05:46  startup     INFO     Checking files
2020-12-01 12:05:46  startup     INFO     Checking subtraction FASTA files
2020-12-01 12:05:46  startup     INFO     Checking index JSON files
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    virtool.config.entry()
  File "/home/tiansheng/Desktop/virtool/virtool/config.py", line 294, in entry
    cli(auto_envvar_prefix="VT", default_map=default_map)
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/tiansheng/Desktop/virtool/virtool/config.py", line 308, in start_server
    asyncio.get_event_loop().run_until_complete(virtool.app.run_app(kwargs))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/tiansheng/Desktop/virtool/virtool/app.py", line 165, in run_app
    runner = await create_app_runner(
  File "/home/tiansheng/Desktop/virtool/virtool/app.py", line 146, in create_app_runner
    await runner.setup()
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/aiohttp/web_runner.py", line 232, in setup
    self._server = await self._make_server()
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/aiohttp/web_runner.py", line 331, in _make_server
    await self._app.startup()
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/aiohttp/web_app.py", line 389, in startup
    await self.on_startup.send(self)
  File "/home/tiansheng/Desktop/virtool/virtool/lib/python3.8/site-packages/aiohttp/signals.py", line 34, in send
    await receiver(*args, **kwargs)  # type: ignore
  File "/home/tiansheng/Desktop/virtool/virtool/startup.py", line 351, in init_tasks
    reference_task = await virtool.tasks.db.register(db, "remove_directory", context={"user_id": "virtool"})
  File "/home/tiansheng/Desktop/virtool/virtool/tasks/db.py", line 18, in register
    "step": virtool.tasks.steps.FIRST_STEPS[task_type],
KeyError: 'remove_directory'
```
This is a bug related to [this PR](https://github.com/virtool/virtool/pull/1968), the `key` should be `delete_reference` instead of `remove_directory`. I will submit a new pull request to fix it.

**Comment by igboyes** [comment]
Thanks. I noticed that too.
