### ISSUE TITLE
History patching exception

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#228]
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
  File "/home/travis/build/virtool/virtool/virtool/error_pages.py", line 14, in middleware_handler
  File "/home/travis/build/virtool/virtool/virtool/app_auth.py", line 96, in middleware_handler
  File "/home/travis/build/virtool/virtool/virtool/handlers/analyses.py", line 19, in get
  File "/home/travis/build/virtool/virtool/virtool/sample_analysis.py", line 142, in format_analysis
  File "/home/travis/build/virtool/virtool/virtool/virus_history.py", line 183, in patch_virus_to_version
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/dictdiffer/__init__.py", line 279, in patch
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/dictdiffer/__init__.py", line 262, in change
TypeError: 'NoneType' object does not support item assignment

```

**Comment by igboyes** [comment]
Caused by an issue unique to the instance.
