### ISSUE TITLE
SubprocessStreamProtocol exception

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#229]
```
Exception in callback <bound method SubprocessStreamProtocol.pipe_data_received of <SubprocessStreamProtocol stdout=<StreamReader 165264 bytes t=<ReadUnixTransport closed=False reading=False 0x7f4f11f84170>> stderr=<StreamReader eof t=<ReadUnixTransport closed=True reading=False 0x7f4f11aca048>>>>
handle: <Handle SubprocessStreamProtocol.pipe_data_received>
```

```
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48426)
  File "/opt/python/3.6.3/lib/python3.6/asyncio/subprocess.py", line 72, in pipe_data_received
  File "/opt/python/3.6.3/lib/python3.6/asyncio/streams.py", line 425, in feed_data
  File "uvloop/handles/stream.pyx", line 671, in uvloop.loop.UVStream.pause_reading (uvloop/loop.c:75249)
RuntimeError: Cannot pause_reading() when closing
```

**Comment by igboyes** [comment]
Duplicate of #262

**Comment by igboyes** [comment]
Duplicate of #262
