### ISSUE TITLE
Event loop stopped before future complete

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#230]
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run.py", line 68, in <module>
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 460, in run_app
  File "uvloop/loop.pyx", line 1201, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25601)
RuntimeError: Event loop stopped before Future completed.
```

**Comment by igboyes** [comment]
This is caused by forcing termination of a closing Virtool instance.
