### ISSUE TITLE
Web page not reloaded after setup

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#231]
Hi Ian,
Exiting to see the 2.0 beta is online.
I downloaded it, input ./run in the terminal, go to localhost:9950, finish setting up each step, and click the upper right "Save and reload" button. But nothing happened. I am still on the setup page.

Zhenhua

**Comment by igboyes** [comment]
What happens if your refresh the browser?

**Comment by maplexuci** [comment]
Did that, the same.

**Comment by maplexuci** [comment]
And when I close everything, and open a new terminal and ./run again, There messages show up:

Traceback (most recent call last):
  File "/home/travis/build/virtool/virtool/virtool/virus.py", line 526, in upgrade_legacy_virus
KeyError: 'username'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/build/virtool/virtool/virtool/virus.py", line 529, in upgrade_legacy_virus
KeyError: 'user_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run.py", line 72, in <module>
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 422, in run_app
  File "uvloop/loop.pyx", line 1203, in uvloop.loop.Loop.run_until_complete (uvloop/loop.c:25636)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 259, in startup
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/signals.py", line 51, in send
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/signals.py", line 17, in _send
  File "/home/travis/build/virtool/virtool/virtool/app.py", line 95, in init_db
  File "/home/travis/build/virtool/virtool/virtool/organize.py", line 17, in organize_viruses
  File "/home/travis/build/virtool/virtool/virtool/virus.py", line 605, in upgrade_legacy_virus_and_history
  File "/home/travis/build/virtool/virtool/virtool/virus.py", line 531, in upgrade_legacy_virus
KeyError: 'user'

**Comment by igboyes** [comment]
Can you please delete the ``settings.json`` file in your install directory and execute ``./run`` again?

**Comment by maplexuci** [comment]
Now I can go to setup page again. But still can not be reloaded. Here is the message shown up in the terminal after I clicked the "save and reload" button.

2017-11-03 17:16:43  web_protocol ERROR    Error handling request
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 422, in start
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 306, in _handle
  File "/home/travis/build/virtool/virtool/virtool/error_pages.py", line 14, in middleware_handler
  File "/home/travis/build/virtool/virtool/virtool/setup.py", line 277, in save_and_reload
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/motor/core.py", line 158, in __getitem__
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/motor/core.py", line 203, in __init__
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/database.py", line 106, in __init__
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pymongo/database.py", line 47, in _check_name
pymongo.errors.InvalidName: database names cannot contain the character '.'
2017-11-03 17:16:43  helpers     INFO     127.0.0.1 - - [03/Nov/2017:21:16:43 +0000] "GET /setup/save HTTP/1.1" 500 330 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
2017-11-03 17:16:45  helpers     INFO     127.0.0.1 - - [03/Nov/2017:21:16:45 +0000] "GET / HTTP/1.1" 302 182 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"
2017-11-03 17:16:45  helpers     INFO     127.0.0.1 - - [03/Nov/2017:21:16:45 +0000] "GET /setup HTTP/1.1" 200 6349 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.102 Safari/537.36"

**Comment by igboyes** [comment]
Damn, you are good at this.

> database names cannot contain the character '.'

Use a database name with no . in it.

I will put a check for this.

**Comment by maplexuci** [comment]
All good now!

**Comment by igboyes** [comment]
Excellent. Keep the bugs coming.
