### ISSUE TITLE
Error when run the PathoscopeBowtie

### ISSUE THREAD

**Issue by maplexuci** [virtool/virtool#240]
2017-11-08 12:06:41  web         ERROR    Exception in callback <bound method AgnosticBaseCursor._to_list of AsyncIOMotorCursor(<pymongo.cursor.Cursor object at 0x7fa32824d0b8>)>
handle: <Handle AgnosticBaseCursor._to_list>
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/motor/core.py", line 878, in _to_list
asyncio.base_futures.InvalidStateError: invalid state

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 49, in uvloop.loop.Handle._run (uvloop/loop.c:48426)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/motor/core.py", line 885, in _to_list
asyncio.base_futures.InvalidStateError: invalid state

**Comment by igboyes** [comment]
Duplicate of #212
