### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#257]
https://sentry.io/virtool/client/issues/409510354/

```
TypeError: Cannot read property '0' of undefined
  at n.hits.reduce.name (/static/app.fdeeace7.js:1:1370281)
  at Array.reduce (<anonymous>)
  at None (/static/app.fdeeace7.js:1:1370206)
  at Array.forEach (<anonymous>)
  at None (/static/app.fdeeace7.js:1:1370155)
...
(18 additional frame(s) were not displayed)
```

**Comment by igboyes** [comment]
This is a problem in exporting the ORF sequences.

```
const content = this.props.results.reduce((orfs, result) => {
            result.orfs.forEach(orf => {
                // Get the best hit for the current ORF.
                if (orf.hits.length) {
                    const bestHit = orf.hits.reduce((result, hit) => {
                        if (hit.full_e < result.e) {
                            result.e = hit.full_e;
                            result.name = hit.definition[0];
                        }

                        return result;
                    }, {name: null, e: 10});

                    if (bestHit.name) {
                        orfs.push(
                            `>orf_${result.index}_${orf.index}|${sampleName}|${bestHit.name}\n${orf.pro}`
                        );
                    }
                }
            });

            return orfs;
        }, []);
```
