### ISSUE TITLE
TypeError: n is null

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#268]
https://sentry.io/virtool/client/issues/410505439/

```
TypeError: n is null
  at g._updateRenderedComponent (/static/app.fcee04dc.js:1:854514)
  at g._performComponentUpdate (/static/app.fcee04dc.js:1:854337)
  at g.updateComponent (/static/app.fcee04dc.js:1:853615)
  at g.receiveComponent (/static/app.fcee04dc.js:1:852732)
  at o<.receiveComponent (/static/app.fcee04dc.js:1:177097)
...
(45 additional frame(s) were not displayed)
```

**Comment by igboyes** [comment]
Close for now. Using sourcemaps with Sentry will give more context to this error if it occurs again.
