### ISSUE TITLE
TypeError: e is null

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#269]
https://sentry.io/virtool/client/issues/410505426/

```
TypeError: e is null
  at o<.getHostNode (/static/app.fcee04dc.js:1:176849)
  at g.getHostNode (/static/app.fcee04dc.js:1:851333)
  at o<.getHostNode (/static/app.fcee04dc.js:1:176856)
  at g._updateRenderedComponent (/static/app.fcee04dc.js:1:854649)
  at g._performComponentUpdate (/static/app.fcee04dc.js:1:854337)
...
(45 additional frame(s) were not displayed)
```

**Comment by igboyes** [comment]
Close for now. Using sourcemaps with Sentry will give more context to this error if it occurs again.
