### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#315]
```python
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
  File "run.py", line 58, in <module>
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web.py", line 479, in run_app
  File "uvloop/loop.pyx", line 1362, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.

```

**Comment by igboyes** [comment]
Duplicate of #314
