### ISSUE TITLE
TypeError during analysis of some samples

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#37]
Getting this exceptions during some analyses:

```
Traceback (most recent call last):
File "virtool/job.py", line 116, in run
File "virtool/analysis.py", line 217, in pathoscope
TypeError: 'NoneType' object is not subscriptable
```

This occurs during the Pathoscope stage of PathoscopeBowtie. Not if it occurs during PathoscopeSNAP. Is this due to having no high-quality mappings for that sample (ie. it is clean).

One CPH sample that causes this error is 16TFP146.

**Comment by igboyes** [comment]
![image](https://cloud.githubusercontent.com/assets/5943558/23087963/1c76a62a-f52d-11e6-93b9-39cc17e7d5e7.png)

**Comment by igboyes** [comment]
![image](https://cloud.githubusercontent.com/assets/5943558/23087977/43d40eec-f52d-11e6-806a-504dd2810065.png)

**Comment by igboyes** [comment]
Issue is caused by spaces in accessions (_id) for sequence documents. These **must** be stripped on entry.
