### ISSUE TITLE
Unhandled exception during software update

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#52]
This exception is raised during the software update.

```
Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fdc147e6158>, <tornado.concurrent.Future object at 0x7fdc34074438>)
Traceback (most recent call last):
  File "site-packages/tornado/ioloop.py", line 604, in _run_callback
  File "site-packages/tornado/stack_context.py", line 275, in null_wrapper
  File "site-packages/tornado/ioloop.py", line 619, in <lambda>
  File "site-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "site-packages/tornado/gen.py", line 1021, in run
  File "virtool/updates.py", line 180, in install_update
  File "site-packages/tornado/gen.py", line 1015, in run
  File "site-packages/tornado/concurrent.py", line 237, in result
  File "<string>", line 3, in raise_exc_info
  File "site-packages/tornado/gen.py", line 270, in wrapper
  File "/home/igboyes/.virtualenvs/virtool/lib/python3.5/types.py", line 243, in wrapped
  File "virtool/web.py", line 265, in _reload
  File "virtool/web.py", line 89, in initialize
  File "virtool/dispatcher.py", line 54, in add_interface
ValueError: Dispatcher already has interface with name 'settings'
```

Software update install needs more testing overall!

**Comment by igboyes** [comment]
This has been resolved as a side-effect.
