### ISSUE TITLE
Closed websocket handler

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#768]
This error occurs, most likely when a websocket connection is not properly closed:
```python
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x2dd1f88>; the handler is closed
```

This may be causing the hanging job bugs that are occuring on the CPH instance.

**Comment by igboyes** [comment]
Full traceback:
```python
Traceback (most recent call last):
  File "/home/travis/build/virtool/virtool/virtool/bio.py", line 458, in wait_for_blast_result
  File "/home/travis/build/virtool/virtool/virtool/app_dispatcher.py", line 137, in dispatch
  File "/home/travis/build/virtool/virtool/virtool/app_dispatcher.py", line 16, in send
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_ws.py", line 195, in send_json
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/web_ws.py", line 184, in send_str
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/http_websocket.py", line 615, in send
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/aiohttp/http_websocket.py", line 583, in _send_frame
  File "uvloop/handles/stream.pyx", line 636, in uvloop.loop.UVStream.write
  File "uvloop/handles/handle.pyx", line 165, in uvloop.loop.UVHandle._ensure_alive
RuntimeError: unable to perform operation on <TCPTransport closed=True reading=False 0x2dd1f88>; the handler is closed
```
