### ISSUE TITLE
KeyError: 'otus'

### ISSUE THREAD

**Issue by Miminko** [virtool/virtool#835]
Importing a reference seems to stop at the `validate_documents` step.

`Traceback (most recent call last):
  File "/home/naomis/Projects/virtool/virtool/db/references.py", line 790, in finish_import
    verify=True
  File "/home/naomis/Projects/virtool/virtool/references.py", line 37, in check_import_data
    errors = detect_duplicates(import_data["otus"])
KeyError: 'otus'
`

**Comment by igboyes** [comment]
Download a fresh reference file from [virtool/ref-plant-viruses](https://github.com/virtool/ref-plant-viruses/releases/tag/v0.1.2).

The old ones will not work anymore.

Reopen if this is still not working.
