### ISSUE TITLE
HMM installation UI

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#874]
Retrofit old HMM installation UI to new API model.

HMM installation has been updated to more closely match the reference installation process. The response from `GET /api/hmms` now includes a `status` field containing information about the installation state of the HMM collection.

More status information can be retrieved using other new endpoints. The `status.installed` and `status.process` fields will be key for rendering the installation process.

**Comment by Miminko** [comment]
@igboyes 
I'm getting a server error when I try to install the official HMMs:
`POST /api/hmms/status/updates 500 (Internal Server Error)`.

This results in the [sentry error](https://sentry.io/cph/server/issues/585016564/?query=is:unresolved) 
```
Traceback (most recent call last):
  File "/home/naomis/.virtualenvs/virtool/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File "/home/naomis/.virtualenvs/virtool/lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
  File "/home/naomis/.virtualenvs/virtool/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 88, in impl
    return await handler(request)
  File "/home/naomis/Projects/virtool/virtool/http/errors.py", line 16, in middleware
    response = await handler(req)
  File "/home/naomis/Projects/virtool/virtool/http/proxy.py", line 68, in middleware
    return await handler(req)
  File "/home/naomis/Projects/virtool/virtool/app_auth.py", line 100, in middleware
    response = await handler(req)
  File "/home/naomis/Projects/virtool/virtool/http/routes.py", line 81, in wrapped
    return await handler(req)
  File "/home/naomis/Projects/virtool/virtool/api/hmm.py", line 115, in install
    release_id
  File "/home/naomis/Projects/virtool/virtool/github.py", line 97, in get_release
    raise virtool.errors.GitHubError("Encountered error {}".format(resp.status))
virtool.errors.GitHubError: Encountered error 404
```

**Comment by Miminko** [comment]
Should the POST request be sending data?

**Comment by Miminko** [comment]
Does this mean that all references to `state.hmms.process` should be replaced with `state.hmms.status.process`?

**Comment by igboyes** [comment]
Yes it should work without data. I'll fix this. For now send:
```json
{
    "release_id": 8460302
}
```
