### ISSUE TITLE
TypeError: Cannot read property 'check' of undefined

### ISSUE THREAD

**Issue by igboyes** [virtool/virtool#960]
https://sentry.io/cph/client/issues/601410566/

```
TypeError: Cannot read property 'check' of undefined
  at Object.value [as onSelect] (/static/app.5cd7060f.js:254:18298)
  at value (/static/app.5cd7060f.js:254:14135)
  at Object.<anonymous> (/static/app.5cd7060f.js:299:688)
  at Object.invokeGuardedCallback (/static/app.5cd7060f.js:299:755)
  at Object.invokeGuardedCallbackAndCatchFirstError (/static/app.5cd7060f.js:299:870)
...
(13 additional frame(s) were not displayed)
```

**Comment by igboyes** [comment]
Manifests as un-checkable checkbox in samples list.
